# Generated by Django 3.0.3 on 2020-11-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='attributes',
            field=models.CharField(default='[]', max_length=2000),
        ),
        migrations.AddField(
            model_name='object',
            name='attributes',
            field=models.CharField(default='{}', max_length=3000),
        ),
    ]
