# Generated by Django 3.0.3 on 2020-11-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201113_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='object',
            name='attributes',
        ),
        migrations.CreateModel(
            name='ObjectAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=3000)),
                ('related_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ClassAttribute')),
                ('related_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Object')),
            ],
        ),
        migrations.AddField(
            model_name='classattribute',
            name='related_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Class'),
        ),
    ]
