# Generated by Django 3.0.3 on 2020-11-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201113_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='parent',
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='ObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_child_obj', to='backend.Object')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_parent_obj', to='backend.Object')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_obj', to='backend.Relation')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_child_class', to='backend.Class')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_parent_class', to='backend.Class')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_class', to='backend.Relation')),
            ],
        ),
    ]
