# Generated by Django 3.0.3 on 2020-11-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201115_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='second_item',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='first_item',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('parent', 'child', 'relation')},
        ),
    ]
