# Generated by Django 3.0.3 on 2020-11-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201115_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='resource',
            name='place_of_storage',
            field=models.CharField(default='Не указано', max_length=300),
        ),
        migrations.AddField(
            model_name='resource',
            name='title_origin',
            field=models.CharField(default='Не указано', max_length=300),
        ),
    ]
