# Generated by Django 3.0.3 on 2020-11-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201122_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTexts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(blank=True, null=True, upload_to='backend.File/bytes/filename/mimetype')),
                ('translation', models.FileField(blank=True, null=True, upload_to='backend.File/bytes/filename/mimetype')),
                ('commentary', models.FileField(blank=True, null=True, upload_to='backend.File/bytes/filename/mimetype')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_name', to='backend.Resource')),
            ],
        ),
    ]
