# Generated by Django 3.0.3 on 2020-11-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_resourcetexts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcetexts',
            old_name='resource_type',
            new_name='resource',
        ),
    ]
