# Generated by Django 3.0.3 on 2020-11-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20201122_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('obj', 'markup', 'position_start', 'position_end')},
        ),
    ]
