# Generated by Django 3.0.3 on 2020-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20201124_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
